name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 45.117.153.128 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run commands on VPS
        env:
          VPS_USER: administrator
          VPS_HOST: 45.117.153.128
          VPS_PORT: 22
        run: |
          ssh -p $VPS_PORT -o UserKnownHostsFile=~/.ssh/known_hosts \
            $VPS_USER@$VPS_HOST <<'EOF'
          echo "Connected successfully!"
          whoami
          uptime
          EOF
