name: Simple Print Test

on:
  push:
    branches:
      - main

jobs:
  print_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "✅ Hello Gogthea! Your GitHub Action ran successfully."
