name: SSH to Windows VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Using Password Authentication with sshpass
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
    
    - name: Test Connection
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o PubkeyAuthentication=no \
          administrator@45.117.153.128 'echo "Connected successfully" && powershell -Command "Get-Date; hostname; whoami"'
    
