name: SSH to Windows VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 45.117.153.128 >> ~/.ssh/known_hosts
    
    - name: Connect to Windows VPS via SSH
      run: |
        ssh -o StrictHostKeyChecking=no administrator@45.117.153.128 << 'EOF'
          echo "Connected to Windows VPS"
          whoami
          hostname
          # Add your commands here
          # Example: PowerShell commands
          powershell -Command "Get-Date"
          powershell -Command "Get-ComputerInfo | Select-Object WindowsVersion, OsArchitecture"
        EOF
    
    # Alternative: Using password authentication (less secure)
    - name: Connect using sshpass (password auth)
      if: false  # Set to true to use this method
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@45.117.153.128 << 'EOF'
          echo "Connected with password"
          powershell -Command "Get-Date"
        EOF
